"""remove FeedType

Revision ID: a9da2e8aa252
Revises: 9f2f6787f076
Create Date: 2026-02-05 20:50:04.552072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9da2e8aa252'
down_revision: Union[str, Sequence[str], None] = '9f2f6787f076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'feed_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('feed_type', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
