"""remove-comments-and-article-topics

Revision ID: c58001af9870
Revises: 9d5a4486b291
Create Date: 2026-04-05 12:51:15.997600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c58001af9870'
down_revision: Union[str, Sequence[str], None] = '9d5a4486b291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('article_topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_topic',
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'topic_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('sentiment', sqlite.JSON(), nullable=True),
    sa.Column('topics', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
